// Set pins and IO ports
#define LED_PERIPH SYSCTL_PERIPH_GPIOF
#define LED_BASE GPIO_PORTF_BASE
#define RED_LED   GPIO_PIN_1
#define BLUE_LED  GPIO_PIN_2
#define GREEN_LED GPIO_PIN_3

#define STP1_PERIPH SYSCTL_PERIPH_GPIOD
#define STP1_BASE GPIO_PORTD_BASE
#define STP1_PLS  GPIO_PIN_1
#define STP1_DIR  GPIO_PIN_2
#define STP1_ENA  GPIO_PIN_3

#define TM1_PERIPH  SYSCTL_PERIPH_GPIOA
#define TM1_BASE  GPIO_PORTA_BASE
#define TM1_CLK   GPIO_PIN_2
#define TM1_DIO   GPIO_PIN_3
#define TM1_STB   GPIO_PIN_4

extern unsigned long g_ulFlags;

